project:
  type: website

website:
  title: "Le bloc-notes Maths, Info, Lycée"
  favicon: favicon.png
  site-url: https://flallemand.fr/blog
  description: "Le blog de M. LALLEMAND, professeur de mathématiques"
  repo-url: https://github.com/fabricelallemand15/blog
  repo-actions: [edit, issue]
  page-navigation: true
  navbar:
    background: light
    logo: avatar.png
    right:
      - about.qmd
      - icon: github
        href: https://github.com/fabricelallemand15/blog
      - icon: mastodon
        href: https://mastodon.mim-libre.fr/@lallemandfabrice
      - icon: instagram
        href: https://www.instagram.com/flallemandprof/
      - icon: youtube
        href: https://www.youtube.com/@flallemandmath
      - icon: rss
        href: index.xml
  page-footer: 
    left:
      - href: http://creativecommons.org/licenses/by/4.0/
        text: <img alt="Licence Creative Commons" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" />
    right: 
      - text: "Mentions légales"
        href: about.qmd
      - icon: github
        href: https://github.com/fabricelallemand15/blog
  cookie-consent: true

bibliography: references.bib

format:
  html:
    lang: fr
    link-external-icon: true
    include-in-header:
      - ajouts_header.html
    theme:
      light: flatly
      # dark: darkly
    css: styles.css
    toc: true
    biblio-title: "Sources utilisées"
    grid:
      sidebar-width: 250px
      body-width: 1000px
      margin-width: 300px
    code-block-border-left: "#31BAE9"
    code-block-bg: true
    comments: 
      giscus: 
        repo: fabricelallemand15/blog
        language: fr
    lightbox: auto



